### ISSUE TITLE
改变代理服务器监听的地址

### ISSUE THREAD

**Issue by developer-ken** [project-mirai/mirai-login-solver-selenium#14]
我在一台debian服务器上运行该插件，该服务器无图形界面，因此我无法在本机上完成验证。而且我无法使用服务器ip+端口的形式连接到插件生成的代理服务器，因为插件监听的地址是localhost，无法使用外部ip连接。请问是否能更改监听ip？

**Comment by aess-a** [comment]
同问题

**Comment by Peiiii** [comment]
同问
