### ISSUE TITLE
Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by xiguafz** [project-mirai/mirai-login-solver-selenium#19]
2021-02-07 16:35:39 W/net.mamoe.mirai-login-solver-selenium: Using HttpProxyServer mode

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Mirai Selenium - HTTP Proxy Server running on 25671

**Comment by Karlatemp** [comment]
SLF4J 与 mirai-login-solver-selenium 无关

`2021-02-07 16:35:39 W/net.mamoe.mirai-login-solver-selenium: Using HttpProxyServer mode`
代表 selenium 无法以默认模式运行，使用 fallback 策略
