### ISSUE TITLE
请问传回的ticket应如何使用

### ISSUE THREAD

**Issue by YuKanJiu** [project-mirai/mirai-login-solver-selenium#22]
如题

**Comment by triplrqin** [comment]
https://github.com/project-mirai/mirai-login-solver-selenium/issues/13#issuecomment-765863733

这个是基于selenium的，意思是需要 Chromedriver来配合。如果Chromedriver设置得当的话（版本路径之类的 ），会直接弹出 对话框。所以ticket并不需要你自己去操作。

**Comment by Karlatemp** [comment]
输入进 mirai 提示框 / 控制台
