### ISSUE TITLE
DevTools是个什么东西，怎么获取和安装

### ISSUE THREAD

**Issue by Zightch** [project-mirai/mirai-login-solver-selenium#25]

**Comment by Karlatemp** [comment]
![image](https://user-images.githubusercontent.com/30070303/108229426-c7627780-717a-11eb-9bb6-bc1c39670504.png)
![image](https://user-images.githubusercontent.com/45701251/107654382-92a77980-6cbd-11eb-96ad-5db811d89b1f.jpg)
![image](https://user-images.githubusercontent.com/45701251/103439547-cdf36900-4c78-11eb-8045-cbf56c8bca4f.jpg)
