### ISSUE TITLE
无法在idea中下载

### ISSUE THREAD

**Issue by Nambers** [project-mirai/mirai-login-solver-selenium#31]
报错如图
![image](https://user-images.githubusercontent.com/35139537/114404462-49e64100-9bd8-11eb-93c4-ab560a3d54bb.png)
依赖
![image](https://user-images.githubusercontent.com/35139537/114404503-54083f80-9bd8-11eb-9c6e-8b228497fa65.png)

**Comment by Him188** [comment]
bintray 炸了

**Comment by Nambers** [comment]
> bintray 炸了

那有什么解决方法吗hhh
自己build？还是用之前的版本还是找jcenter看看有没有快照

**Comment by Him188** [comment]
> > bintray 炸了
> 
> 那有什么解决方法吗hhh
> 自己build？还是用之前的版本还是找jcenter看看有没有快照

正在上传 central

可以先用手动方法处理

**Comment by Nambers** [comment]
@Him188 是已经部署好了吗

**Comment by Karlatemp** [comment]
Try `1.0-dev-17`?

**Comment by Nambers** [comment]
> Try `1.0-dev-17`?

ok我试试

**Comment by Nambers** [comment]
可以了
