### ISSUE TITLE
请教关于滑块验证网页地址的问题

### ISSUE THREAD

**Issue by LittleUnicat** [project-mirai/mirai-login-solver-selenium#34]
如题，我在mcl中登录需要滑块验证

![}MNZME0I({7{8@H4D `N`_P](https://user-images.githubusercontent.com/65627817/119442470-7a360900-bd5a-11eb-8feb-d838fb58c63a.png)

于是我便跟着readme文件的方式二去解决该问题
但是我不是很理解其中一个步骤的网页应该如何得到

![M2L6 2@V}HW`TVWKA)PJAPW](https://user-images.githubusercontent.com/65627817/119442492-88842500-bd5a-11eb-8481-ba3b58056382.png)

做到这里就卡住了，我的问题是如何得到滑块验证的网页地址，因为我在控制台中登录时没有弹出相应关于验证的网页窗口，安装了该插件也只会显示not support的信息（插件信息爆红不支持），请问各路大佬应该如何解决呢？谢谢。

**Comment by Karlatemp** [comment]
Did you confirm that you read the readme?

https://github.com/project-mirai/mirai-login-solver-selenium/blob/77d5e6a9fd11dce74d9d69cb6c217b794e184879/README.md#L22-L31

**Comment by LittleUnicat** [comment]
> Did you confirm that you read the readme?
> 
> https://github.com/project-mirai/mirai-login-solver-selenium/blob/77d5e6a9fd11dce74d9d69cb6c217b794e184879/README.md#L22-L31

您好，按照说明文件中说的，我已经修改了mcl文件内容
![S2JK5O{R9DC25L$A~NWPK8S](https://user-images.githubusercontent.com/65627817/119481512-5fc55500-bd85-11eb-82cd-00fb896aacfa.png)
我修改的是框中的mcl文件
![N(){)B%F03XV}H2 D_QF~}N](https://user-images.githubusercontent.com/65627817/119481494-5a680a80-bd85-11eb-91b6-bd264b36f866.png)
但是我修改保存之后仍出现问题，请问我是什么步骤出错了吗？
本人是个小白，可能问出的问题可能比较水，希望您多多包涵下^_^

**Comment by Karlatemp** [comment]
无文件后缀的是给Linux，MacOS用的，下面那个mcl.cmd才是Windows用的

**Comment by LittleUnicat** [comment]
> 无文件后缀的是给Linux，MacOS用的，下面那个mcl.cmd才是Windows用的

是这样，谢谢您，问题解决了^_^
