### ISSUE TITLE
登陆报错,怎么解决

### ISSUE THREAD

**Issue by Zightch** [project-mirai/mirai-login-solver-selenium#36]
Login failed: Error(bot=Bot(), code=237, title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备 上登录或稍后再试。, errorInfo=), tips=若频繁出现, 请尝试开启设备锁
![image](https://user-images.githubusercontent.com/60181569/120908273-08838680-c69b-11eb-8cd3-c7708a5c90dc.png)

**Comment by Karlatemp** [comment]
提供网络日志， 位于 bots/./

**Comment by Ripperso** [comment]
同样错误，日志

[0m2021-06-10 17:29:44 V/Net xxx: No BdhSession cache[0m
[0m2021-06-10 17:29:44 V/Net xxx: No server list cached.[0m
[92m2021-06-10 17:29:44 I/Net xxx: Connected to server 113.96.12.224:8080[0m
[0m2021-06-10 17:29:44 V/Net xxx: Send: wtlogin.login[0m
[0m2021-06-10 17:29:44 V/Net xxx: Recv: LoginPacketResponse.Captcha.Slider[0m
[0m2021-06-10 17:30:22 V/Net xxx: Send: wtlogin.login[0m
[0m2021-06-10 17:30:23 V/Net xxx: Recv: Error(bot=Bot(xxx), code=237, title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=)[0m
[0m2021-06-10 17:30:23 V/Net xxx: Channel closed.[0m
