### ISSUE TITLE
 windows，输入ticket后提示，code=237, title=禁止登录

### ISSUE THREAD

**Issue by Ripperso** [project-mirai/mirai-login-solver-selenium#37]
Win10系统，Nox安卓模拟器，mirai-console1.0.5 
![image](https://user-images.githubusercontent.com/23456134/121618486-6d731e00-ca99-11eb-91ed-4339d5e779e0.png)

日志
[0m2021-06-11 09:29:25 V/Net xxx: No BdhSession cache[0m
[0m2021-06-11 09:29:25 V/Net xxx: No server list cached.[0m
[92m2021-06-11 09:29:25 I/Net xxx: Connected to server 157.255.13.77:14000[0m
[0m2021-06-11 09:29:25 V/Net xxx: Send: wtlogin.login[0m
[0m2021-06-11 09:29:25 V/Net xxx: Recv: LoginPacketResponse.Captcha.Slider[0m
[92m2021-06-11 09:29:25 I/Net xxx: Connected to server 157.255.13.77:14000[0m
[0m2021-06-11 09:29:25 V/Net xxx: Send: wtlogin.login[0m
[0m2021-06-11 09:29:25 V/Net xxx: Recv: LoginPacketResponse.Captcha.Slider[0m
[0m2021-06-11 09:29:25 V/Net xxx: Channel closed.[0m
[0m2021-06-11 09:30:30 V/Net xxx: No BdhSession cache[0m
[0m2021-06-11 09:30:30 V/Net xxx: No server list cached.[0m
[92m2021-06-11 09:30:30 I/Net xxx: Connected to server 203.205.255.221:8080[0m
[0m2021-06-11 09:30:30 V/Net xxx: Send: wtlogin.login[0m
[0m2021-06-11 09:30:30 V/Net xxx: Recv: LoginPacketResponse.Captcha.Slider[0m
[0m2021-06-11 09:31:28 V/Net xxx: Send: wtlogin.login[0m
[0m2021-06-11 09:31:29 V/Net xxx: Recv: Error(bot=Bot(xxx), code=237, title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=)[0m
[0m2021-06-11 09:31:29 V/Net xxx: Channel closed.[0m

**Comment by Karlatemp** [comment]
![$HH](https://user-images.githubusercontent.com/30070303/121625895-f5135980-caa6-11eb-9ea7-84165b619d72.png)
