### ISSUE TITLE
关于设备锁验证网页无法输入的问题

### ISSUE THREAD

**Issue by shitlime** [project-mirai/mirai-login-solver-selenium#38]
滑块的问题可以解决，但是又遇到了新的问题
![image](https://user-images.githubusercontent.com/31384673/122637280-4f07c500-d120-11eb-90c9-bbbb49a7244a.png)
这应该是QQ的设备锁，我点击“设备锁验证”后，弹出来的网页无法输入和点击
![image](https://user-images.githubusercontent.com/31384673/122637364-cd646700-d120-11eb-83ae-cb14c2b0af60.png)
已经尝试使用手机访问该网页、换浏览器访问该网页等各种方法，目前依旧无法输入。

**Comment by Karlatemp** [comment]
用手机QQ打开

**Comment by shitlime** [comment]
> 用手机QQ打开

感谢提供思路，已经成功解决。

在这里为遇到类似问题的朋友们留个方法
用手机QQ还是无法输入，但是多了一个扫码的选项，点进去立刻截图二维码，然后点扫一扫用相册的截图扫码成功解决。
![12EA08C6A443B1891972A14A047BB943](https://user-images.githubusercontent.com/31384673/122647915-3536a400-d159-11eb-8c5f-215da85f1ece.jpg)
