### ISSUE TITLE
看不到滑块验证链接？

### ISSUE THREAD

**Issue by dragon0629** [project-mirai/mirai-login-solver-selenium#4]
HI？

请问是我哪里操作不对吗0_0 
好像没看到浏览器用的滑块验证码链接？之前M1-1的时候还是有的。
![ISSUE](https://user-images.githubusercontent.com/29683336/103267654-efd8bb80-49ec-11eb-92ba-c687d9f71e44.png)

**Comment by dragon0629** [comment]
![ISSUE](https://user-images.githubusercontent.com/29683336/103268074-d421e500-49ed-11eb-9412-915a127902fb.png)

**Comment by Karlatemp** [comment]
请尝试将本模块添加至运行时或添加至 mirai-console/plugins，并且不要添加 mirai.c.....support参数

**Comment by dragon0629** [comment]
我MIRAI目录结构是这样的

\config\Console\...5个yml(AutoLogin.yml,Command.yml,ExtensionSelector.ymlLogger.yml.PermissionService.yml)
\data\MiraiNative
\jre(内置的JRE环境)
\libs\mirai-console-2.0-M2-all.jar
\libs\mirai-console-terminal-2.0-M2-all.jar
\libs\mirai-core-2.0-M2-all.jar
\libs\ **mirai-login-solver-selenium-1.0-dev-6.jar**
\MxLibData\selenium..
\plugins\mirai-native-1.9.6.jar
start.bat

bat 启动方法为：java -cp "./libs/*" net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader 

另:去掉mirai.c.....support参数后直接连输入ticket的弹窗都没了

**Comment by Karlatemp** [comment]
使用该模块时不需要添加 mirai.....support 参数

**Comment by Karlatemp** [comment]
> 我MIRAI目录结构是这样的
> 
> \config\Console...5个yml(AutoLogin.yml,Command.yml,ExtensionSelector.ymlLogger.yml.PermissionService.yml)
> \data\MiraiNative
> \jre(内置的JRE环境)
> \libs\mirai-console-2.0-M2-all.jar
> \libs\mirai-console-terminal-2.0-M2-all.jar
> \libs\mirai-core-2.0-M2-all.jar
> \libs\ **mirai-login-solver-selenium-1.0-dev-6.jar**
> \MxLibData\selenium..
> \plugins\mirai-native-1.9.6.jar
> start.bat
> 
> bat 启动方法为：java -cp "./libs/*" net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader
> 
> 另:去掉mirai.c.....support参数后直接连输入ticket的弹窗都没了

尝试以插件模式运行

**Comment by dragon0629** [comment]
> > 我MIRAI目录结构是这样的
> > \config\Console...5个yml(AutoLogin.yml,Command.yml,ExtensionSelector.ymlLogger.yml.PermissionService.yml)
> > \data\MiraiNative
> > \jre(内置的JRE环境)
> > \libs\mirai-console-2.0-M2-all.jar
> > \libs\mirai-console-terminal-2.0-M2-all.jar
> > \libs\mirai-core-2.0-M2-all.jar
> > \libs\ **mirai-login-solver-selenium-1.0-dev-6.jar**
> > \MxLibData\selenium..
> > \plugins\mirai-native-1.9.6.jar
> > start.bat
> > bat 启动方法为：java -cp "./libs/*" net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader
> > 另:去掉mirai.c.....support参数后直接连输入ticket的弹窗都没了
> 
> 尝试以插件模式运行

感谢回复，我将mirai-login-solver-selenium-1.0-dev-6.jar 调整至 \plugins\下，启动显示加载2个插件，login 指令后直接红字报错，BAT没有添加mirai.....support 参数

![ISSUE2](https://user-images.githubusercontent.com/29683336/103270707-8f00b180-49f3-11eb-9534-e4d7f4019eba.png)

**Comment by liergazi** [comment]
我和上面的老兄mirai版本一样

**Comment by liergazi** [comment]
我和上面的老兄版本啥的一样mirai-console-2.0-M2-all.jar
mirai-console-terminal-2.0-M2-all.jar
mirai-core-2.0-M2-all.jar
mirai-login-solver-selenium-1.0-dev-6.jar 也是看不到滑块验证2020-12-29 19:20:27 W/Bot.2682553371: java.lang.RuntimeException: org.apache.http.conn.ConnectTimeoutException: Connect to chromedriver.stor
age.googleapis.com:443 [chromedriver.storage.googleapis.com/216.58.200.240] failed: Read timed out
java.lang.RuntimeException: org.apache.http.conn.ConnectTimeoutException: Connect to chromedriver.storage.googleapis.com:443 [chromedriver.s
torage.googleapis.com/216.58.200.240] failed: Read timed out不知道是不是我哪里弄得不对

**Comment by dragon0629** [comment]
我莫名其妙解决了
我把jar拷回到\libs\ mirai-login-solver-selenium-1.0-dev-6.jar 不以插件模式运行加载
这次调出了验证码的CHROME网页

我猜想是因为之前因为某个原因，调起chrome失败了，所以卡在了那一步
因为没有在console里显示验证码的链接，所以就无法继续了

当可以顺利调起chrome的时候就正常了

建议在console窗口显示出完整的验证码页面链接，这样就算没有自动调起chrome窗口
也可以手动复制链接到chrome里打开。

**Comment by liergazi** [comment]
> 我莫名其妙的解决了
> 我把罐子放回到\ libs \ mirai-login-solver-selenium-1.0-dev-6.jar不以插件模式运行加载
> 这次调出了验证码的CHROME网页
> 
> 我猜想是因为之前因为某个原因，调起chrome失败了，所以卡在了那一步
> 因为没有在console里显示验证码的链接，所以就无法继续了
> 
> 当可以顺利调起chrome的时候就正常了
> 
> 建议在控制台窗口中显示出完整的验证码页面链接，这样就算没有自动调启动chrome窗口
> 也可以手动复制链接到chrome里打开。

恭喜恭喜

**Comment by liergazi** [comment]
> 前因为某个原因，调起chrome失败了，所以卡在了那一步
> 因为没有在console里显示验证码的链接

我注意到我好像用的是mirai-login-solver-selenium-1.0-dev-6-all,我也换成你说的mirai-login-solver-selenium-1.0-dev-6.jar。还是报错 2020-12-30 09:10:33 W/Bot.: java.lang.NoClassDefFoundError: io/github/karlatemp/mxlib/selenium/MxSelenium
java.lang.NoClassDefFoundError: io/github/karlatemp/mxlib/selenium/MxSelenium
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt.process(SeleniumLoginSolverImpl.kt:58)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl$onSolveSliderCaptcha$$inlined$suspendCoroutine$lambda$1.invoke(SeleniumLoginSolv
erImpl.kt:36)
        at net.mamoe.mirai.selenium.SeleniumLoginSolverImpl$onSolveSliderCaptcha$$inlined$suspendCoroutine$lambda$1.invoke(SeleniumLoginSolv
erImpl.kt:18)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Caused by: java.lang.ClassNotFoundException: io.github.karlatemp.mxlib.selenium.MxSelenium
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 4 more 头皮发麻

**Comment by liergazi** [comment]
> 我莫名其妙的解决了
> 我把罐子放回到\ libs \ mirai-login-solver-selenium-1.0-dev-6.jar不以插件模式运行加载
> 这次调出了验证码的CHROME网页
> 
> 我猜想是因为之前因为某个原因，调起chrome失败了，所以卡在了那一步
> 因为没有在console里显示验证码的链接，所以就无法继续了
> 
> 当可以顺利调起chrome的时候就正常了
> 
> 建议在控制台窗口中显示出完整的验证码页面链接，这样就算没有自动调启动chrome窗口
> 也可以手动复制链接到chrome里打开。

我也莫名其妙的解决了(浏览器调出滑块页成功)

**Comment by dragon0629** [comment]
建议在控制台窗口中显示出完整的验证码页面链接，这样就算没有自动调启动chrome窗口
也可以手动复制链接到chrome里打开。 谢谢！

**Comment by Karlatemp** [comment]
b968efcd1864e5392cd182bc6921d71559d1052e



dev9



---原始邮件---
发件人: "dragon0629"<notifications@github.com&gt;
发送时间: 2020年12月30日(周三) 晚上6:51
收件人: "project-mirai/mirai-login-solver-selenium"<mirai-login-solver-selenium@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Karlatemp"<karlatemp@vip.qq.com&gt;;
主题: Re: [project-mirai/mirai-login-solver-selenium] 看不到滑块验证链接？ (#4)




 
建议在控制台窗口中显示出完整的验证码页面链接，这样就算没有自动调启动chrome窗口
 也可以手动复制链接到chrome里打开。 谢谢！
