### ISSUE TITLE
使用Mirai Console Loader时设置手动完成滑动验证的JVM参数怎么添加

### ISSUE THREAD

**Issue by ctycode** [project-mirai/mirai-login-solver-selenium#9]
使用Mirai Console Loader时设置手动完成滑动验证的JVM参数怎么添加呀
![9692651D45AF06B2DFD9B4D7BB449B18](https://user-images.githubusercontent.com/56985178/104415888-ca7fac00-55ad-11eb-944b-93a3e257e6e7.jpg)

**Comment by Karlatemp** [comment]
已补全相关文档

https://github.com/project-mirai/mirai-login-solver-selenium/blob/master/README.md#%E6%89%8B%E5%8A%A8%E5%AE%8C%E6%88%90%E6%BB%91%E5%8A%A8%E9%AA%8C%E8%AF%81
